aircraft:
  name: nTop UAV
  units: US
  mass: 234.8
  inertia:
    Ixx: 14908.4
    Iyy: 2318.4
    Izz: 17226.9
    Ixz: 0.0
  reference:
    S: 199.94
    b: 19.89
    c: 26.689
  aerodynamics:
    type: linear
    rho: 0.002377
    derivatives:
      CL_0: 0.2
      CL_alpha: 4.5
      CL_q: 3.5
      CL_elevator: 0.4
      CD_0: 0.03
      CD_alpha2: 0.8
      Cm_0: 0.0
      Cm_alpha: -0.6
      Cm_q: -8.0
      Cm_elevator: -1.2
      CY_beta: -0.3
      Cl_beta: -0.1
      Cl_p: -0.5
      Cl_r: 0.1
      Cl_aileron: 0.15
      Cn_beta: 0.08
      Cn_p: -0.05
      Cn_r: -0.2
      Cn_aileron: -0.02
  propulsion:
    type: propeller
    power_max: 50.0
    diameter: 6.0
    efficiency: 0.75
    offset:
    - 0.0
    - 0.0
    - 0.0
  initial_state:
    altitude: 5000.0
    airspeed: 200.0
    pitch: 2.0
    roll: 0.0
    yaw: 0.0
